### PR TITLE
Enable use of remote graph

### PR DESCRIPTION
**Pull request by otaviojava**

### CODE REVIEW

**Comment by bsorrentino** [comment]
Hi @otaviojava 

I've quickly reviewed your implementation, below my comments:

* Use of Graph object
   > When use remote connection, the Graph Object is , usually, an [**empty graph**](http://tinkerpop.apache.org/javadocs/3.2.2/full/org/apache/tinkerpop/gremlin/structure/util/empty/EmptyGraph.html) so it is , really, not usable. This will imply that we need a **specialised** implementation that use, exclusively, a `GraphTraversalSource` 
* Use GraphTraversalSource object
   > Use of `GraphTraversalSource` implies to minimise/remove usage of **detached Vertex/Edge** and emphasise usage of  fluent transaction that means exec more steps in one command

Make sense ? What do you think ?

**Comment by otaviojava** [comment]
Yes, that is just a draft, we'll have a new implementation with GraphTraversalSource to GraphTemplate, Repository, and Producer.

**Comment by otaviojava** [comment]
I did just to converter, what do you think @bsorrentino ?
Is that ok?

**Comment by bsorrentino** [comment]
Hi @otaviojava this implementation looks perfectly fit traversalsource usage

I can’t wait to use it

**Comment by otaviojava** [comment]
test this please

**Pull request merged**
