### PR TITLE
Enable use of remote graph

### PR DESCRIPTION
**Pull request by bsorrentino**
concerning issue #27 this PR contains the updates need to enable **remote graph** usage

* Removed usage of `Graph` object
* disable usage of `addEdge` on `Vertex`
* Allow access to `GraphTraversalSource`
* Disable the possibility to update both `Vertex` and `Edge` outside Traversal operation

### CODE REVIEW

**Comment by genie-jnosql** [comment]
Can one of the admins verify this patch?

**Comment by furlaneto** [comment]
Hello @bsorrentino!
Thanks for the contribution, but first, you have to sign de ECA (https://www.eclipse.org/legal/ecafaq.php) and sign your commit with "-s" option, like this: git commit -s -m "message".
For all Eclipse projects you have to do this.
Thanks.

**Comment by otaviojava** [comment]
Hey, I love this PR, congratulations.
But what I have in my mind is create a new implementation, but this one using remote graph.
So, keep the current classes, add a new implementation using it.

Again, congratulations on the initiative.

**Comment by bsorrentino** [comment]
Firstly I didn't know that there was ECA .. I've subscribe it just now

Firstly I didn't know that there was ECA .. I've subscribe it just now

I Like this project so I've just tried to implemented what I needed following your strategy

I've understood that you are think about a new **fresh** implementation in this case I'd like to give you my feedbacks based on what I've seen:

Your approach is to wrapping  traversal. Since there are a lot of **Steps** in traversal  implementation there is a risk to have a **partial implementation** so I'd like to have a clear separation between **Object Graph Mapping** API   and **Traversal Wrapping** API, this will make usage of such framework more comfortable & flexible.

Thank you for sharing and giving the opportunity to contribute

**Comment by otaviojava** [comment]
Hum, that makes sense.
Perhaps, a @Transversal Qualifier to both.
I really like to have both options.
WDYT?

**Comment by otaviojava** [comment]
Hey @bsorrentino what do you think about this approach?
Could you review this draft proposal?
https://github.com/eclipse/jnosql-artemis-extension/pull/29

**Pull request closed without merging**
